mac/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from . import settings
from django.conf.urls.static import static 
from django.conf.urls import url
from django.views.static import serve

admin.site.site_header = "iCoder Admin"
admin.site.site_title = "iCoder Admin Panel"
admin.site.index_title = "Welcome to iCoder Admin Panel"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),

    path('signup',views.signup,name='signup'),
    path('login',views.userlogin,name='login'),
    path('logout/',views.userlogout,name='logout'),

    path('changepass/', views.MyPasswordChangeView.as_view(), name='changepass'), 
    path('password_change_done/', views.MyPasswordChangeDoneView.as_view(), name='password_change_done'),
    
    path('password_reset/', views.MyPasswordResetView.as_view(),name='password_reset'),
    path('password_reset/done/', views.MyPasswordResetDoneView.as_view(),name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.MyPasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('reset/done/', views.MyPasswordResetCompleteView.as_view(),name='password_reset_complete'),

    url(r'^media/(?P<path>.*)$', serve,{'document_root':  settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.fields import IntegerField
from django.utils.timezone import now

# Create your models here.
class Blogpost(models.Model):
    post_id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=50)
    category = models.CharField(max_length=50,default='')
    views= models.IntegerField(default=0)
    views_by = models.CharField(max_length=500,default='',blank=True)
    description = models.TextField(blank=True,default='')
    pub_date = models.DateField(default=now)
    thumbnail = models.ImageField(upload_to='images/blog_images', default="",null=True)
    upload_by = models.CharField(max_length=200,default='',blank=True)

    def __str__(self):
        return self.title


class BlogComment(models.Model):
    sno = models.AutoField(primary_key=True)
    comment = models.TextField(blank=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)
    blog = models.ForeignKey(Blogpost,on_delete=models.CASCADE,null=True)
    parent = models.ForeignKey('self', on_delete=models.CASCADE,null=True) ## parent is field of self.model 
  
    reply = models.BooleanField(default=False,null=True)

    timestamp = models.DateTimeField(default=now) ## don't need add time when comment submitted

    def __str__(self):
        return str(self.sno)

templates/base.html
{% load static %}
{% get_static_prefix as STATIC_PREFIX%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{{STATIC_PREFIX}}mac/css/all.min.css">
    <link rel="stylesheet" href="{{STATIC_PREFIX}}mac/css/bootstrap.min.css">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-uWxY/CJNBR+1zjPWmfnSnVxwRheevXITnMqoEIeG1LJrdI0GlVs/9cVSyPYXdcSF" crossorigin="anonymous">

    
    {% comment %} 1. Owl Carousel Min. css {% endcomment %}
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" integrity="sha512-tS3S5qG0BlhnQROyJXvNjeEM4UpMXHrQfTGmbQ1gKmelCxlSEBUaxhRBj/EFTzpbP4RVSrpEikbmdJobCvhE3g==" crossorigin="anonymous" referrerpolicy="no-referrer" />

        {% comment %} 2. Owl Carousel Theme Min. css {% endcomment %}
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css" integrity="sha512-sMXtMNL1zRzolHYKEujM2AqCLUR9F2C4/05cdbxjjLSRvMQIciEPCQZo++nk7go3BtSuK9kfa/s+a4f4i5pLkw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

<!--    {% block app_css %}<link rel="stylesheet" href="{{STATIC_PREFIX}}mac/css/mac.css">{% endblock app_css %}-->
    <link rel="stylesheet" href="{{STATIC_PREFIX}}mac/css/shop.css">
     <script async defer crossorigin="anonymous" src="https://connect.facebook.net/mr_IN/sdk.js#xfbml=1&version=v12.0" nonce="jvS9600J"></script>
</head>
<body id='top'>
     {% block navbar %} {% include 'navbar_blog.html' %}  {% endblock navbar %}
     
     {% if messages %}
            {% for message in messages %}
                {% comment %} {% if message.tags %} {{ message.tags }} {% endif %} {% endcomment %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
    {% endif %}


    {% block body %}{% endblock body %}
    
    <script>

        let previews = document.getElementsByClassName('preview')
        Array.from(previews).forEach((element)=>{
        element.innerHTML = element.innerText;
        })

    </script>

    <script src="{{STATIC_PREFIX}}mac/js/all.min.js"></script>
    <script src="{{STATIC_PREFIX}}mac/js/jquery-3.6.0.min.js"></script>
    <script src="{{STATIC_PREFIX}}mac/js/popper.min.js"></script>
    <script src="{{STATIC_PREFIX}}mac/js/bootstrap.min.js"></script>

    {% comment %} let's include cdn files {% endcomment %}
        {% comment %} 0. Jquery Cdn {% endcomment %}
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

        {% comment %} 1. Owl Carousel Min .js {% endcomment %}
        <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js" integrity="sha512-bPs7Ae6pVvhOSiIcyUClR7/q2OAsRiovw4vAkX+zJbw3ShAeeqezq50RIIcIURq7Oa20rW2n2q+fyXBNcU9lrw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

        {% comment %} Init Owl Carousel {% endcomment %}
            <script>
                $('.owl-carousel').owlCarousel({
                        loop:true,
                        margin:10,
                        nav:true,
                        responsive:{
                            0:{
                                items:1
                            },
                            600:{
                                items:3
                            },
                            1000:{
                                items:5
                            }
                        }
                    })
            </script>

    


{% comment %} Custom js {% endcomment %}
        {% comment %} Below File Not Working For Custom JavaScript {% endcomment %}
        <script src="static/mac/js/shop.js"></script> 

        {% comment %} But this one working For Custom JavaScript {% endcomment %}
        {% include 'custom_javascript.html' %}



    <footer class="footer mt-auto py-2 bg-dark">
        <div class="container text-center text-white">
            <a class="btn btn-outline-primary mb-2"  href="#top"> Back to Top</a><br>
            <span class="">© Designed and Developed by Pritam Ramteke</span>
        </div>
    </footer>

</body>
</html>

templates/changepass.html
{% extends 'base.html' %}
{% block title %}Change Password{% endblock title %}
{% load static %}


{% block body %} 

<style>
    
</style>
<br>
{% comment %} User Registration Form {% endcomment %}
    <div class="container  mx-auto mt-5 mb-5">

        <h2 class='text-center'>Change Password</h2>
        
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8 ">
                <form action="" method='POST'  style="border: Solid 1px; padding:20px;" novalidate>
                    {% csrf_token %}
                    {% for fm in form %}
                        <span > <label for="{{fm.auto_id}}">{{fm.label_tag}}</label>  <input type="{{ fm.field.widget.input_type }}" name="{{fm.name}}" class="form-control" maxlength="150" autofocus required id="{{fm.auto_id}}"> 

                        <span style='color:red; font-size:12px;'>{{fm.errors|striptags}}</span>
                    <br>
                    <br>
                    {% endfor %}
                
                    <input type="submit" class=' btn btn-warning'  value='Change Password'>
                    <a href="{% url 'dashboard' %}" class='btn btn-info'>Cancel</a>
                </form>
            </div>
        </div>
        
    </div>


{% endblock body %}

templates/custom_javascript.html
<script>

 // console.log('working'); 

var dataURL = `/Json/`
$.ajax({
    method: 'GET',
    url: dataURL,
    success:function(response){
        // console.log('RESPONSE:', response)
        // console.log('RESPONSE:', response.length)
        document.getElementById('cart').innerHTML = response.length;
    }
    
    })

// TinyMCE javascript
var script = document.createElement('script');
script.type = 'text/javascript';
script.src = "https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js"

document.head.appendChild(script);

 tinymce.init({
        selector: '#id_description', // This id get by fetching syntax using inspect django admin panel model field


        
        plugins: [
      'advlist autolink link image lists charmap print preview hr anchor pagebreak',
      'searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking',
      // 'table emoticons template paste help'
    ],
    toolbar: 'undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | ' +
      'bullist numlist outdent indent | link image | print preview media fullscreen | ' +
      'forecolor backcolor emoticons | help',
    menu: {
      favs: {title: 'My Favorites', items: 'code visualaid | searchreplace | emoticons'}
    },
    menubar: 'favs file edit view insert format tools table help',
    content_css: 'css/content.css'
      });
    

</script>

templates/login.html
{% extends 'base.html' %}
{% block title %}Login{% endblock title %}
{% load static %}
{% block body %}
<div class="row mx-0" style='min-height:66vh; margin-top:15vh;'>
  <div class="col-md-3"></div>
  <div class="col-md-6 my-3">
    <h2 class='text-center'>Login</h2>
    <form method="post" action='/login'>
      {% csrf_token %}
      <div >
        <label for="username" class="form-label">Username</label>
        <input type="text" class="form-control" id="username" name='username' placeholder='Enter your username'
          required>
      </div>
      <div class="mb-3">
        <label for="pass1" class="form-label">Password</label>
        <input type="password" name='pass1' class="form-control" id="pass1" placeholder='Enter your password' required>
      </div>
      <button type="submit" class="btn btn-primary">Login</button>
      <a href="{% url 'signup' %}" class="btn btn-primary">SignUp</a>
      <a href="{% url 'password_reset' %}" class="btn btn-primary">Forget Password</a>
    </form>
  </div>

  <div class="col-md-3"></div>
</div>

{% endblock body %}

templates/mhome.html
{% extends 'base.html' %}
{% block title %}ShopHome{% endblock title %}
{% load static %}
{% block navbar %} {% include 'navbar.html' %} {% endblock navbar %}

{% block body %} 

<h1> I am MainHome Page </h1>

<br>

{% endblock body %}

templates/navbar_blog.html
<style>
  .navbar-dark .navbar-nav .nav-link:hover {
    color: white;
    opacity: .8;
  }

  .navbar-dark .navbar-nav .nav-link:hover {
    color: white;
    opacity: 1;
  }

  .navbar-dark .navbar-nav .nav-link.active {
    color: white;
  }
</style>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'bhome' %}">Blog</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <nav class="collapse navbar-collapse " id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <a class="nav-link {{home}}" aria-current="page" href="{% url 'bhome' %}">Home</a>
        </li>

      </ul>


      <span class='d-flex'>
        <ul class="navbar-nav me-auto mb-2 mb-lg-0 ">
          {% if request.user.is_authenticated %}

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Welcome {{request.user|capfirst}}
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="{% url 'blog_dashboard' %}">Profile</a></li>
              <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
            </ul>
          </li>


          {% else %}
          <li class="nav-item mx-2">
            <a class="nav-link {{login}} " href="{% url 'login' %}"> Login </a>
          </li>

          <li class="nav-item">
            <a class="nav-link {{signup}} " href="{% url 'signup' %}"> SignUp </a>
          </li>
          {% endif %}
        </ul>
      </span>
      <form method='get' action='../blogsearch/' class='d-flex '>
          <input class="form-control me-2 search_form" type="search" placeholder="Search" aria-label="Search"
            name='search' id='search'>
          <button class="btn btn-success" type="submit">Search</button>
      </form>
    

    </nav>
  </div>
</nav>

templates/password_change_done.html
{% extends 'base.html' %}
{% block title %} Change Password Done {% endblock title %}

{% block body %}

    <h2> Your Password Change Sucessfully </h2>
    
    <a href="{% url 'home' %}"> Goto  Home</a>
    {% comment %} <a href="{% url 'login' %}"> Goto  Login</a> {% endcomment %}

{% endblock body %}

templates/password_reset.html
{% extends 'base.html' %}
{% block title %}Password Reset{% endblock title %}

{% block body %}

    <h2>Password Reset Form</h2>
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {% for fm in form %}
            {{fm.label_tag}}{{fm}} <span style="color:red; font-size:12px;">{{fm.errors}}</span> <br><br>
        {% endfor %}
        <input type="submit" class='btn btn-success' value="Reset Password">
        <a href="{% url 'home' %}" class="btn btn-info"> Cancel </a>
    </form>

{% endblock body %}

templates/password_reset_complete.html
{% extends 'base.html' %}
{% block title %}Password Reset Complete{% endblock title %}

{% block body %}

    <h2> Your Password Reset Sucessfully </h2>

    
    <a class=" {{login}} btn btn-success" data-bs-toggle="modal" data-bs-target="#loginModal"> Login </a>
    
{% endblock body %}

templates/password_reset_confirm.html
{% extends 'base.html' %}
{% block title %}Password Reset{% endblock title %}

{% block body %}

    <h2>Password Reset Confirm Form</h2>
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {% for fm in form %}
            {{fm.label_tag}}{{fm}} <span style="color:red; font-size:12px;">{{fm.errors}}</span> <br><br>
        {% endfor %}
        <input type="submit" class='btn btn-success' value="Reset Password">
        <a href="{% url 'home' %}" class="btn btn-info"> Cancel </a>
    </form>

{% endblock body %}

templates/password_reset_done.html
{% extends 'base.html' %}
{% block title %}Password Reset Done{% endblock title %}

{% block body %}

    <div class="alert alert-info ">
       <strong> Password reset sent </strong> <br>
       <p>
       We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.
       </p>

       <p>
        If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.
       </p>
    
    </div>
    
{% endblock body %}

templates/prac.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Get Text Input Field Value in JavaScript</title>
</head>
<body>
<p id="demo"></p>
<script>
document.getElementById("demo").innerHTML = 5 + 6;
</script>
</body>
</html>

templates/signup.html
{% extends 'base.html' %}
{% block title %}Signup{% endblock title %}
{% load static %}


{% block body %}
    <div class="row mx-0">
      <div class="col-md-3"></div>
      <div class="col-md-6 my-4">
          <h2 class='text-center'> SignUp </h2>
          <form action='/signup' method='POST'>
          {% csrf_token %}
          <div class="mb-3">
            <label for="username" class="form-label">Username </label>
            <input type="text" class="form-control" id="username" name='username'
              placeholder='Choose a unique username (lowercase & alphanumeric)' required>
          </div>

          <div class="mb-3">
            <label for="fname" class="form-label">First_Name</label>
            <input type="text" class="form-control" id="fname" name='fname' placeholder='First Name'>
          </div>

          <div class="mb-3">
            <label for="lname" class="form-label">Last_Name</label>
            <input type="text" class="form-control" id="lname" name='lname' placeholder='Last Name'>
          </div>


          <div class="mb-3">
            <label for="email" class="form-label">Email address</label>
            <input type="email" class="form-control" id="email" name='email' aria-describedby="emailHelp"
              placeholder='name@example.com' required>
            <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
          </div>

          <div class="mb-3">
            <label for="pass1" class="form-label">Password</label>
            <input type="password" class="form-control" id="pass1" name='pass1' placeholder='Choose your password'
              required>
          </div>

          <div class="mb-3">
            <label for="pass2" class="form-label">Confirm_Password</label>
            <input type="password" class="form-control" id="pass2" name='pass2' placeholder='Enter your password again'
              required>
          </div>

          <div >
          <button type="submit" class="btn btn-primary">SignUp</button>
          Already Registered <a href="{% url 'login' %}">Login Here</a>
          </div>
        </form>

      </div>
      <div class="col-md-3"></div>
    </div>



{% endblock body %}